#//---------------------------------------------------------------------------//
#// Copyright (c) 2018-2019 Nil Foundation AG
#// Copyright (c) 2018-2019 Mikhail Komarov <nemo@nil.foundation>
#// Copyright (c) 2019 Moskvin Aleksey <zerg1996@yandex.ru>
#//

language: cpp

sudo: true

python: "2.7"

jobs:
  include:

      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-7']
        env:
            - CXX=g++-7 CXXSTD=c++11


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-8']
        env:
            - CXX=g++-8 CXXSTD=c++11


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-9']
        env:
            - CXX=g++-9 CXXSTD=c++11


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-7']
        env:
            - CXX=g++-7 CXXSTD=c++14


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-8']
        env:
            - CXX=g++-8 CXXSTD=c++14


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-9']
        env:
            - CXX=g++-9 CXXSTD=c++14


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-7']
        env:
            - CXX=g++-7 CXXSTD=c++1z


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-8']
        env:
            - CXX=g++-8 CXXSTD=c++1z


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-9']
        env:
            - CXX=g++-9 CXXSTD=c++1z


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-7']
        env:
            - CXX=g++-7 CXXSTD=c++17


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-8']
        env:
            - CXX=g++-8 CXXSTD=c++17


      - compiler: gcc
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test']
                packages: ['g++-9']
        env:
            - CXX=g++-9 CXXSTD=c++17


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
                packages: ['clang-5.0', 'g++-7']
        env:
            - CXX=clang++-5.0 CXXSTD=c++11


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
                packages: ['clang-6.0', 'g++-7']
        env:
            - CXX=clang++-6.0 CXXSTD=c++11


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
                packages: ['clang-7', 'g++-7']
        env:
            - CXX=clang++-7 CXXSTD=c++11


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
                packages: ['clang-8', 'g++-7']
        env:
            - CXX=clang++-8 CXXSTD=c++11


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
                packages: ['clang-5.0', 'g++-7']
        env:
            - CXX=clang++-5.0 CXXSTD=c++14


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
                packages: ['clang-6.0', 'g++-7']
        env:
            - CXX=clang++-6.0 CXXSTD=c++14


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
                packages: ['clang-7', 'g++-7']
        env:
            - CXX=clang++-7 CXXSTD=c++14


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
                packages: ['clang-8', 'g++-7']
        env:
            - CXX=clang++-8 CXXSTD=c++14


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
                packages: ['clang-5.0', 'g++-7']
        env:
            - CXX=clang++-5.0 CXXSTD=c++1z


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
                packages: ['clang-6.0', 'g++-7']
        env:
            - CXX=clang++-6.0 CXXSTD=c++1z


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
                packages: ['clang-7', 'g++-7']
        env:
            - CXX=clang++-7 CXXSTD=c++1z


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
                packages: ['clang-8', 'g++-7']
        env:
            - CXX=clang++-8 CXXSTD=c++1z


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-5.0']
                packages: ['clang-5.0', 'g++-7']
        env:
            - CXX=clang++-5.0 CXXSTD=c++17


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-6.0']
                packages: ['clang-6.0', 'g++-7']
        env:
            - CXX=clang++-6.0 CXXSTD=c++17


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-7']
                packages: ['clang-7', 'g++-7']
        env:
            - CXX=clang++-7 CXXSTD=c++17


      - compiler: clang
        os: linux
        dist: xenial
        addons:
            apt:
                sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
                packages: ['clang-8', 'g++-7']
        env:
            - CXX=clang++-8 CXXSTD=c++17



before_install:
    - if [[ $TRAVIS_OS_NAME == linux && $TRAVIS_COMPILER == clang ]]; then
        sudo apt-get update;
        wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -;
        sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-${COMPILER_VERSION} main";
        sudo apt-get update && sudo apt-get install clang-${COMPILER_VERSION};
        export CC=/usr/bin/clang-${COMPILER_VERSION};
        export CXX=/usr/bin/clang++-${COMPILER_VERSION};
      fi
    - if [[ $TRAVIS_OS_NAME == linux && $TRAVIS_COMPILER == gcc ]]; then
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
        sudo apt-get install gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION};
        export CC=/usr/bin/gcc-${COMPILER_VERSION};
        export CXX=/usr/bin/g++-${COMPILER_VERSION};
      fi


install:
    - cd ..
    - git clone --depth 1 https://github.com/boostorg/boost.git boost-root;
    - cd boost-root
    - git submodule update --init tools/build
    - git submodule update --init libs/config
    - git submodule update --init tools/boost_install
    - git submodule update --init libs/headers
    - git submodule update --init tools/boostdep
    - git submodule update --init libs/multiprecision
    - git submodule update --init libs/container
    - git submodule update --init libs/accumulators
    - python tools/boostdep/depinst/depinst.py multiprecision
    - python tools/boostdep/depinst/depinst.py container
    - python tools/boostdep/depinst/depinst.py accumulators
    - ./bootstrap.sh
    - cat bootstrap.log
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew upgrade;
      fi

script:
    - clang++
    - |-
        echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        proc=$(($(nproc) + 1));
        elif [[ $TRAVIS_OS_NAME == osx ]]; then
        proc=$(($(sysctl -n hw.ncpu) + 1));
      fi;
    - sudo ./b2 -j$proc install;
    - cd $TRAVIS_BUILD_DIR && mkdir cmake-build && cd cmake-build;
    - echo $CXXSTD
    - cmake -DBUILD_SHARED_LIBS=TRUE -DBUILD_TESTS=TRUE -DCMAKE_CXX_STANDARD=$(echo $CXXSTD | sed 's/[^0-9z]*//g') ..;
    - make -j$proc tests-codec;
    - ctest .

notifications:
    email:
        on_success: always
