name: Set version

on:
  # Triggers the workflow on push to master branch
  push:
    branches: [ master ]

jobs:
  autotag_version:
    name: Auto tag version
    runs-on: [ubuntu-latest]
    env:
      VERSION_FILE_NAME: VERSION
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check if version was changed
      uses: technote-space/get-diff-action@v6
      with:
        FILES: ${{ env.VERSION_FILE_NAME }}

    - name: Tag new version
      if: ${{ env.MATCHED_FILES }}
      run: |
        version=$(cat ${{ env.VERSION_FILE_NAME }})
        git tag v$version

    - name: Push tags
      if: ${{ env.MATCHED_FILES }}
      uses: ad-m/github-push-action@master
      with:
        tags: true
