name: Build docs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: [self-hosted]

    env:
      DOXYFILE_NAME: "crypto3.doxyfile"
      BUILD_DIR: "doxygen_build"

    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SUITE_REPO }}
          submodules: recursive

      - name: Cmake and build
        env:
          CMAKE_ARGS: "-DBUILD_SHARED_LIBS=TRUE -DBUILD_TESTS=TRUE -DDOXYGEN_OUTPUT_DIR=${{ env.BUILD_DIR }}"
        run: cmake ${{env.CMAKE_ARGS}} ..

      - name: Build doxygen
        working-directory: ./build
        run: doxygen ${{ env.DOXYFILE_NAME }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCS_STAGING_SSH_KEY }}
          known_hosts: ${{secrets.DOCS_STAGING_KNOWN_HOSTS}}
          if_key_exists: ignore

      - name: Deploy on remote host
        env:
          HOST: ${{ secrets.DOCS_STAGING_HOST }}
          USER: ${{ secrets.DOCS_STAGING_USER }}
          TARGET_DIR: '/home/docs/build'
          OPTIONS: '-avz --progress --delete'
        run: rsync ${{ env.OPTIONS }} ${{ env.BUILD_DIR }}/ ${{ env.USER }}@${{ env.HOST }}:${{ env.TARGET_DIR }}
