name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check-proof-producer:
    name: Check Proof Producer
    uses: ./.github/workflows/check-proof-producer.yml
    if: |
      always() && !cancelled()
    secrets: inherit

