name: Run tests

on:
  # Let's run it on any commit
  [push]
  # Triggers the workflow on pull request events but only for the master branch
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

env:
  SUITE_REPO: "NilFoundation/crypto3"
  CACHE_NAME: "checkout-job-cache"

jobs:
  checkout:
    runs-on: [self-hosted, tests-runner]
    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout suite
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SUITE_REPO }}
          submodules: recursive

      - name: Checkout zk
        working-directory: .
        run: |
          cd libs/zk
          git checkout origin/162-github-actions

      - name: Checkout zk-marshalling
        working-directory: .
        run: |
          cd libs/zk-marshalling
          git checkout origin/43-remove-blueprint-dependency

      - name: Cmake and build
        env:
          CMAKE_ARGS: "
            -DCMAKE_BUILD_TYPE=Debug
            -DBUILD_SHARED_LIBS=FALSE
            -DBUILD_TESTS=TRUE
            -DZK_PLACEHOLDER_PROFILING=TRUE
            "
        run: |
          mkdir build
          cd build
          cmake ${{ env.CMAKE_ARGS }} ..

      - name: Archive build results
        run: |
          touch ${{ env.CACHE_NAME }}.tar.gz
          tar -czf ${{ env.CACHE_NAME }}.tar.gz --exclude=${{ env.CACHE_NAME }}.tar.gz .

      - name: Cache archived job output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CACHE_NAME }}
          path: ${{ env.CACHE_NAME }}.tar.gz
          retention-days: 1